In [30]:
import numpy as np

# 1. Setup your details
STUDENT_NAME = "Roxie Nacional"
STUDENT_ID_STR = "TUPM-25-0363"

# 2. Convert ID to an integer so numpy can use it
# This takes "TUPM-25-0363" and turns it into 250363
student_id_int = int(''.join(filter(str.isdigit, STUDENT_ID_STR)))

# 3. Seed the generator for reproducibility
np.random.seed(student_id_int)

# 4. Generate the array
# Range is 1 to (remainder of ID/100 + 50)
upper_bound = (student_id_int % 100) + 50
data = np.random.randint(1, upper_bound, size=10)

# 5. Calculations
mean_val = np.mean(data)
std_val = np.std(data)

# 6. Output
print(f"--- Results for {STUDENT_NAME} ---")
print(f"Generated Array: {data}")
print(f"Mean:            {mean_val:.2f}")
print(f"Std Dev:         {std_val:.2f}")

--- Results for Roxie Nacional ---
Generated Array: [ 26  46  30  68  85 100  39  57  20 106]
Mean:            57.70
Std Dev:         29.42


In [31]:
import numpy as np

STUDENT_NAME = "Roxie Nacional"
STUDENT_ID_STR = "TUPM-25-0363"

# Convert ID string to integer for seeding and math
student_id_int = int(''.join(filter(str.isdigit, STUDENT_ID_STR)))

# Set seed for consistency
np.random.seed(student_id_int)

# Create a 3x4 matrix
# Max value will be (250363 % 50) + 20 = 13 + 20 = 33
upper_bound = (student_id_int % 50) + 20
matrix = np.random.randint(1, upper_bound, size=(3, 4))

print(f"{STUDENT_NAME}'s Matrix:")
print(matrix)
print("-" * 20)

# Calculate sums along different axes
row_sums = np.sum(matrix, axis=1) # Summing across columns
col_sums = np.sum(matrix, axis=0) # Summing down rows

print("Row sums (horizontal):", row_sums)
print("Column sums (vertical):", col_sums)

Roxie Nacional's Matrix:
[[26 14 30  4]
 [21 24 23  4]
 [ 7 25 20 10]]
--------------------
Row sums (horizontal): [74 72 62]
Column sums (vertical): [54 63 73 18]


In [32]:
import numpy as np

STUDENT_NAME = "Roxie Nacional"
STUDENT_ID_STR = "TUPM-25-0363"

# Convert string ID to integer
student_id_int = int(''.join(filter(str.isdigit, STUDENT_ID_STR)))

# Set the seed
np.random.seed(student_id_int)

# Create a 3x3x3 3D Array
# Range: 0 to (250363 % 20 + 10) -> 0 to 13
upper_bound = (student_id_int % 20) + 10
arr3d = np.random.randint(0, upper_bound, size=(3, 3, 3))

print(f"{STUDENT_NAME}'s 3D Array:\n", arr3d)

# Slicing the "middle" layer across the Y-axis
slice_mid = arr3d[:, 1, :]
print("\nSlice[:, 1, :]:\n", slice_mid)

Roxie Nacional's 3D Array:
 [[[ 9  3  4]
  [ 7  6  3]
  [ 6  8  3]]

 [[ 9  6  4]
  [11  4  1]
  [ 4  3 10]]

 [[ 4  0  7]
  [ 8  8  5]
  [ 2  5  7]]]

Slice[:, 1, :]:
 [[ 7  6  3]
 [11  4  1]
 [ 8  8  5]]


In [33]:
import numpy as np

STUDENT_NAME = "Roxie Nacional"
STUDENT_ID_STR = "TUPM-25-0363"

# Convert ID string to integer
student_id_int = int(''.join(filter(str.isdigit, STUDENT_ID_STR)))

# Set the seed
np.random.seed(student_id_int)

# 1. Create the original array (Range: 1 to 113)
x = np.random.randint(1, (student_id_int % 100) + 50, size=10)

# 2. Define the filter boundaries
lower_limit = student_id_int % 50   # 13
upper_limit = student_id_int % 100  # 63

# 3. Boolean Indexing
# This creates a "mask" of True/False values
filtered = x[(x > lower_limit) & (x < upper_limit)]

print(f"{STUDENT_NAME}'s Original:", x)
print(f"Lower limit: {lower_limit}, Upper limit: {upper_limit}")
print("Filtered subset:", filtered)

Roxie Nacional's Original: [ 26  46  30  68  85 100  39  57  20 106]
Lower limit: 13, Upper limit: 63
Filtered subset: [26 46 30 39 57 20]


In [34]:
import numpy as np

STUDENT_NAME = "Roxie Nacional"
STUDENT_ID_STR = "TUPM-25-0363"

# Convert ID string to integer
student_id_int = int(''.join(filter(str.isdigit, STUDENT_ID_STR)))

# Set the seed
np.random.seed(student_id_int)

# Create two 2x2 matrices
# Max value: (250363 % 50) + 20 = 33
limit = (student_id_int % 50) + 20
A = np.random.randint(1, limit, size=(2, 2))
B = np.random.randint(1, limit, size=(2, 2))

print(f"--- {STUDENT_NAME}'s Matrices ---")
print("Matrix A:\n", A)
print("Matrix B:\n", B)

# Matrix Multiplication (Dot Product)
product = A @ B

# Linear Algebra: Determinant
det_A = np.linalg.det(A)

print("\nMatrix Product (A @ B):\n", product)
print(f"Determinant of A: {det_A:.2f}")

--- Roxie Nacional's Matrices ---
Matrix A:
 [[26 14]
 [30  4]]
Matrix B:
 [[21 24]
 [23  4]]

Matrix Product (A @ B):
 [[868 680]
 [722 736]]
Determinant of A: -316.00


In [35]:
import numpy as np

STUDENT_NAME = "Roxie Nacional"
STUDENT_ID_STR = "TUPM-25-0363"

# Convert ID string to integer (though not used for a seed here, 
# it's good practice for consistency in your assignments)
student_id_int = int(''.join(filter(str.isdigit, STUDENT_ID_STR)))

# Create 8 equally spaced points between 0 and 2*pi (360 degrees)
# np.linspace is perfect for generating "x-axis" values for graphs
angles = np.linspace(0, 2*np.pi, 8)

sine_vals = np.sin(angles)
cos_vals = np.cos(angles)

print(f"--- Results for {STUDENT_NAME} ---")
print(f"Angles (radians):\n{angles}")
print(f"\nSine values:\n{sine_vals}")
print(f"\nCosine values:\n{cos_vals}")

--- Results for Roxie Nacional ---
Angles (radians):
[0.         0.8975979  1.7951958  2.6927937  3.5903916  4.48798951
 5.38558741 6.28318531]

Sine values:
[ 0.00000000e+00  7.81831482e-01  9.74927912e-01  4.33883739e-01
 -4.33883739e-01 -9.74927912e-01 -7.81831482e-01 -2.44929360e-16]

Cosine values:
[ 1.          0.6234898  -0.22252093 -0.90096887 -0.90096887 -0.22252093
  0.6234898   1.        ]


In [36]:
import numpy as np

STUDENT_NAME = "Roxie Nacional"
STUDENT_ID_STR = "TUPM-25-0363"

# Convert ID string to integer
student_id_int = int(''.join(filter(str.isdigit, STUDENT_ID_STR)))

# Set the seed
np.random.seed(student_id_int)

# Create a 4x4 array
# Range: 1 to (13 + 20) = 33
limit = (student_id_int % 50) + 20
arr = np.random.randint(1, limit, size=(4, 4))

print(f"Original Matrix for {STUDENT_NAME}:")
print(arr)

# Apply strided slicing: arr[start:stop:step, start:stop:step]
# This selects every 2nd row and every 2nd column and sets them to 0
arr[::2, ::2] = 0

print("\nModified 4x4 Array (Checkerboard Pattern):")
print(arr)

Original Matrix for Roxie Nacional:
[[26 14 30  4]
 [21 24 23  4]
 [ 7 25 20 10]
 [32  7  5 12]]

Modified 4x4 Array (Checkerboard Pattern):
[[ 0 14  0  4]
 [21 24 23  4]
 [ 0 25  0 10]
 [32  7  5 12]]


In [37]:
import numpy as np

STUDENT_NAME = "Roxie Nacional"
STUDENT_ID_STR = "TUPM-25-0363"

# Convert ID string to integer
student_id_int = int(''.join(filter(str.isdigit, STUDENT_ID_STR)))

# Set the seed for reproducibility
np.random.seed(student_id_int)

# 1. Generate 10 random scores
# Max score: (250363 % 100) + 50 = 63 + 50 = 113
scores = np.random.randint(0, (student_id_int % 100) + 50, 10)

# 2. Vectorized If-Else (np.where)
# Passing threshold: 250363 % 70 = 33
threshold = student_id_int % 70
grades = np.where(scores >= threshold, 'Pass', 'Fail')

print(f"{STUDENT_NAME}'s Scores:", scores)
print(f"Passing Threshold: {threshold}")
print("Grades:", grades)

Roxie Nacional's Scores: [ 25  45  29  67  84  99  38  56  19 105]
Passing Threshold: 43
Grades: ['Fail' 'Pass' 'Fail' 'Pass' 'Pass' 'Pass' 'Fail' 'Pass' 'Fail' 'Pass']


In [38]:
import numpy as np

STUDENT_NAME = "Roxie Nacional"
STUDENT_ID_STR = "TUPM-25-0363"

# Convert ID string to integer
student_id_int = int(''.join(filter(str.isdigit, STUDENT_ID_STR)))

# Set the seed
np.random.seed(student_id_int)

# 1. Create a 3x4 matrix
limit = (student_id_int % 50) + 20
arr = np.random.randint(1, limit, size=(3, 4))

# 2. Flatten: Convert 2D to 1D
flat_arr = arr.flatten()

# 3. Transpose: Swap rows and columns
transposed_arr = arr.T

print(f"--- {STUDENT_NAME}'s Array Transformations ---")
print("Original 3x4 Matrix:\n", arr)
print("\nFlattened (1x12):\n", flat_arr)
print("\nTransposed (4x3):\n", transposed_arr)

--- Roxie Nacional's Array Transformations ---
Original 3x4 Matrix:
 [[26 14 30  4]
 [21 24 23  4]
 [ 7 25 20 10]]

Flattened (1x12):
 [26 14 30  4 21 24 23  4  7 25 20 10]

Transposed (4x3):
 [[26 21  7]
 [14 24 25]
 [30 23 20]
 [ 4  4 10]]


In [49]:
import numpy as np

STUDENT_NAME = "Roxie Nacional"
STUDENT_ID_STR = "TUPM-25-0363"

# Convert ID string to integer
student_id_int = int(''.join(filter(str.isdigit, STUDENT_ID_STR)))

# Set the seed for reproducibility
np.random.seed(student_id_int)

# Create a 1D array of 10 random integers
limit = (student_id_int % 100) + 50
data = np.random.randint(1, limit, size=10)

print(f"{STUDENT_NAME}'s Array:", data)

# Statistical calculations
mean_val = np.mean(data)
std_val = np.std(data)

print(f"Mean: {mean_val:.2f}")
print(f"Std Dev: {std_val:.2f}")

Roxie Nacional's Array: [ 26  46  30  68  85 100  39  57  20 106]
Mean: 57.70
Std Dev: 29.42


In [50]:
import numpy as np
import pandas as pd

STUDENT_NAME = "Roxie Nacional"
STUDENT_ID_STR = "TUPM-25-0363"

# Convert ID string to integer to fix the TypeError
student_id_int = int(''.join(filter(str.isdigit, STUDENT_ID_STR)))

# Seed for consistency
np.random.seed(student_id_int)

# Create the DataFrame
df = pd.DataFrame({
    'Name': [STUDENT_NAME] * 5,
    'Score': np.random.randint(student_id_int % 50, (student_id_int % 100) + 50, 5),
    'YearsCodePro': np.random.randint(0, (student_id_int % 20) + 10, 5)
})

print("--- Professional Profile DataFrame ---")
print(df)

--- Professional Profile DataFrame ---
             Name  Score  YearsCodePro
0  Roxie Nacional     38             7
1  Roxie Nacional     58             6
2  Roxie Nacional     42             3
3  Roxie Nacional     80             6
4  Roxie Nacional     97             8


In [51]:
import numpy as np
import pandas as pd

STUDENT_NAME = "Roxie Nacional"
STUDENT_ID_STR = "TUPM-25-0363"

# Convert ID string to integer for the seed
student_id_int = int(''.join(filter(str.isdigit, STUDENT_ID_STR)))
np.random.seed(student_id_int)

# 1. Create the DataFrame
df = pd.DataFrame({
    'EdLevel': ['Bachelor', 'Master', 'PhD', 'Bachelor', 'Master'],
    'ConvertedComp': np.random.randint(40000, 150000, 5)
})

# 2. The Split-Apply-Combine process
avg_salary = df.groupby('EdLevel')['ConvertedComp'].mean()

print(f"--- Salary Analysis for {STUDENT_NAME} ---")
print("Original Data:\n", df)
print("\nAverage Salary by Education Level:\n", avg_salary)

--- Salary Analysis for Roxie Nacional ---
Original Data:
     EdLevel  ConvertedComp
0  Bachelor          87385
1    Master          95469
2       PhD          99549
3  Bachelor         113940
4    Master         124087

Average Salary by Education Level:
 EdLevel
Bachelor    100662.5
Master      109778.0
PhD          99549.0
Name: ConvertedComp, dtype: float64


In [52]:
import numpy as np
import pandas as pd

STUDENT_NAME = "Roxie Nacional"
STUDENT_ID_STR = "TUPM-25-0363"

# Convert ID string to integer to fix the TypeError
student_id_int = int(''.join(filter(str.isdigit, STUDENT_ID_STR)))

# Seed for consistency
np.random.seed(student_id_int)

# 1. Create the DataFrame
df = pd.DataFrame({
    'Country': ['Philippines', 'USA', 'UK', 'Canada', 'Germany'],
    'ConvertedComp': np.random.randint(40000, 150000, 5)
})

# 2. Sort the data
# ascending=False puts the highest numbers at the top
top5 = df.sort_values(by='ConvertedComp', ascending=False)

print(f"--- Country Compensation Ranking for {STUDENT_NAME} ---")
print(top5)

--- Country Compensation Ranking for Roxie Nacional ---
       Country  ConvertedComp
4      Germany         124087
3       Canada         113940
2           UK          99549
1          USA          95469
0  Philippines          87385


In [53]:
import numpy as np
import pandas as pd

STUDENT_NAME = "Roxie Nacional"
STUDENT_ID_STR = "TUPM-25-0363"

# Convert ID string to integer to avoid TypeError
student_id_int = int(''.join(filter(str.isdigit, STUDENT_ID_STR)))

# Seed for consistency
np.random.seed(student_id_int)

# 1. Create the DataFrame
df = pd.DataFrame({
    'Name': [STUDENT_NAME] * 5,
    'YearsCodePro': np.random.randint(0, (student_id_int % 20) + 10, 5)
})

# 2. Filter the data
# Condition: YearsCodePro > (250363 % 10), which is 3
threshold = student_id_int % 10
high_exp = df[df['YearsCodePro'] > threshold]

print(f"--- Experience Filter for {STUDENT_NAME} (Threshold: > {threshold}) ---")
print(high_exp)

--- Experience Filter for Roxie Nacional (Threshold: > 3) ---
             Name  YearsCodePro
0  Roxie Nacional             9
2  Roxie Nacional             4
3  Roxie Nacional             7
4  Roxie Nacional             6


In [54]:
import numpy as np
import pandas as pd

STUDENT_NAME = "Roxie Nacional"
STUDENT_ID_STR = "TUPM-25-0363"

# Convert ID string to integer to avoid TypeError
student_id_int = int(''.join(filter(str.isdigit, STUDENT_ID_STR)))

# Seed for consistency
np.random.seed(student_id_int)

# 1. Create the DataFrame with random salaries
df = pd.DataFrame({
    'ConvertedComp': np.random.randint(40000, 150000, 5)
})

# 2. Define the edges of your "buckets"
bins = [0, 50000, 100000, 150000, 200000]
labels = ['0-50k', '50-100k', '100-150k', '>150k']

# 3. Use pd.cut to assign each salary to a bracket
df['Bracket'] = pd.cut(df['ConvertedComp'], bins=bins, labels=labels)

print(f"--- Salary Binning for {STUDENT_NAME} ---")
print(df)

--- Salary Binning for Roxie Nacional ---
   ConvertedComp   Bracket
0          87385   50-100k
1          95469   50-100k
2          99549   50-100k
3         113940  100-150k
4         124087  100-150k


In [55]:
import numpy as np
import pandas as pd

STUDENT_NAME = "Roxie Nacional"
STUDENT_ID_STR = "TUPM-25-0363"

# Convert ID string to integer to fix the TypeError
student_id_int = int(''.join(filter(str.isdigit, STUDENT_ID_STR)))

# Seed for consistency
np.random.seed(student_id_int)

# 1. Create the DataFrame with random salaries
df = pd.DataFrame({
    'ConvertedComp': np.random.randint(40000, 150000, 5)
})

# 2. Apply Log Transformation (Natural Log - base e)
df['LogComp'] = np.log(df['ConvertedComp'])

print(f"--- Log Transformation for {STUDENT_NAME} ---")
print(df)

--- Log Transformation for Roxie Nacional ---
   ConvertedComp    LogComp
0          87385  11.378079
1          95469  11.466557
2          99549  11.508405
3         113940  11.643427
4         124087  11.728738


In [56]:
import numpy as np
import pandas as pd

STUDENT_NAME = "Roxie Nacional"
STUDENT_ID_STR = "TUPM-25-0363"

# Convert ID string to integer to fix the TypeError
student_id_int = int(''.join(filter(str.isdigit, STUDENT_ID_STR)))

# Seed for consistency
np.random.seed(student_id_int)

# 1. Create the DataFrame
df = pd.DataFrame({
    'YearsCodePro': np.random.randint(0, (student_id_int % 20) + 10, 5),
    'ConvertedComp': np.random.randint(40000, 150000, 5)
})

# 2. Calculate the Pearson Correlation Matrix
corr_matrix = df.corr()

print(f"--- Correlation Analysis for {STUDENT_NAME} ---")
print("Original Data:\n", df)
print("\nCorrelation Matrix:\n", corr_matrix)

--- Correlation Analysis for Roxie Nacional ---
Original Data:
    YearsCodePro  ConvertedComp
0             9          74403
1             3          51832
2             4          54227
3             7          60585
4             6          93823

Correlation Matrix:
                YearsCodePro  ConvertedComp
YearsCodePro        1.00000        0.52299
ConvertedComp       0.52299        1.00000


In [57]:
import numpy as np
import pandas as pd

STUDENT_NAME = "Roxie Nacional"
STUDENT_ID_STR = "TUPM-25-0363"

# Convert ID string to integer to fix the TypeError
student_id_int = int(''.join(filter(str.isdigit, STUDENT_ID_STR)))

# Seed for consistency
np.random.seed(student_id_int)

# 1. Create the DataFrame
df = pd.DataFrame({
    'EdLevel': ['Bachelor', 'Master', 'PhD', 'Bachelor', 'Master'],
    'ConvertedComp': np.random.randint(40000, 150000, 5)
})

# 2. Multi-metric Aggregation
# .agg() allows us to run multiple functions at once
summary = df.groupby('EdLevel')['ConvertedComp'].agg(['mean', 'median', 'std']).reset_index()

print(f"--- Education vs Salary Summary for {STUDENT_NAME} ---")
print(summary)

--- Education vs Salary Summary for Roxie Nacional ---
    EdLevel      mean    median           std
0  Bachelor  100662.5  100662.5  18777.220574
1    Master  109778.0  109778.0  20235.981864
2       PhD   99549.0   99549.0           NaN


In [58]:
import numpy as np
import pandas as pd

STUDENT_NAME = "Roxie Nacional"
STUDENT_ID_STR = "TUPM-25-0363"

# Convert string ID to integer for the random seed
student_id_int = int(''.join(filter(str.isdigit, STUDENT_ID_STR)))
np.random.seed(student_id_int)

# 1. Create the DataFrame
df = pd.DataFrame({
    'ConvertedComp': np.random.randint(40000, 150000, 5)
})

# 2. Define the threshold
threshold = 110000

# 3. Create the 'HighPay' column using vectorized logic
# Syntax: np.where(condition, value_if_true, value_if_false)
df['HighPay'] = np.where(df['ConvertedComp'] > threshold, 'Yes', 'No')

print(f"--- Salary Classification for {STUDENT_NAME} ---")
print(df)

--- Salary Classification for Roxie Nacional ---
   ConvertedComp HighPay
0          87385      No
1          95469      No
2          99549      No
3         113940     Yes
4         124087     Yes


In [59]:
import numpy as np
import pandas as pd

STUDENT_NAME = "Roxie Nacional"
STUDENT_ID_STR = "TUPM-25-0363"

# Convert ID string to integer to ensure the code runs
student_id_int = int(''.join(filter(str.isdigit, STUDENT_ID_STR)))

# Seed for consistency
np.random.seed(student_id_int)

# 1. Create the DataFrame
df = pd.DataFrame({
    'Country': ['Philippines', 'USA', 'UK', 'Canada', 'Germany'],
    'ConvertedComp': np.random.randint(40000, 150000, 5)
})

# 2. Group by 'Country' and perform multiple aggregations
top_countries = df.groupby('Country')['ConvertedComp'].agg(['mean', 'max'])

print(f"--- Country-wise Salary Stats for {STUDENT_NAME} ---")
print(top_countries)

--- Country-wise Salary Stats for Roxie Nacional ---
                 mean     max
Country                      
Canada       113940.0  113940
Germany      124087.0  124087
Philippines   87385.0   87385
UK            99549.0   99549
USA           95469.0   95469
