1. Creating NumPy Arrays

In [ ]:
import numpy as np # type: ignore

# 1. 1D Array: Years of Experience (Added 2 points: 12 and 15)
years_exp = np.array([1, 3, 5, 7, 10, 12, 15])
print("Years of Experience (1D Array):")
print(years_exp)
print("-" * 30)

# 2. 2D Array: Salaries (Added 2 rows of sample data)
salaries = np.array([
    [50, 60, 70], 
    [80, 90, 100],
    [110, 120, 130], # New data point 1
    [140, 150, 160]  # New data point 2
])
print("Salary Matrix (2D Array):")
print(salaries)
print("-" * 30)

# 3. Zeros and Ones Arrays
zeros_array = np.zeros((2, 2))
ones_array = np.ones((2, 3))
print("Zeros Array (2x2):\n", zeros_array)
print("\nOnes Array (2x3):\n", ones_array)
print("-" * 30)

# --- "Try It" Section: Identity Matrix ---

# 4. Create a 3x3 Identity Matrix
identity_matrix = np.eye(3)
print("Identity Matrix (3x3):")
print(identity_matrix)

2. Array Operations

In [ ]:
import numpy as np # type: ignore

# Re-establishing the variable from the previous step
years_exp = np.array([1, 3, 5, 7, 10])

# --- Basic Operations ---

# Step 1: Element-wise addition
exp_plus_5 = years_exp + 5
print("Years + 5:", exp_plus_5)

# Step 2: Element-wise multiplication
exp_times_2 = years_exp * 2
print("Years * 2:", exp_times_2)

# Step 3: Dot product
sample1 = np.array([1, 2, 3])
sample2 = np.array([4, 5, 6])
dot_result = np.dot(sample1, sample2)
print("Dot Product:", dot_result)

# --- "Try It" Section: Subtraction, Division, Exp, and Log ---

# Experiment with subtraction and division
exp_minus_1 = years_exp - 1
exp_div_2 = years_exp / 2

# Apply np.exp() and np.log()
# Using sample1 for cleaner log outputs (log(0) is undefined)
exp_values = np.exp(sample1) 
log_values = np.log(sample1)

print("-" * 30)
print("Subtraction (Years - 1):", exp_minus_1)
print("Division (Years / 2):", exp_div_2)
print("Exponential (e^x on [1,2,3]):", exp_values)
print("Natural Log (ln on [1,2,3]):", log_values)

Years + 5: [ 6  8 10 12 15]
Years * 2: [ 2  6 10 14 20]
Dot Product: 32
------------------------------
Subtraction (Years - 1): [0 2 4 6 9]
Division (Years / 2): [0.5 1.5 2.5 3.5 5. ]
Exponential (e^x on [1,2,3]): [ 2.71828183  7.3890561  20.08553692]
Natural Log (ln on [1,2,3]): [0.         0.69314718 1.09861229]


3. Indexing and Slicing

In [ ]:
import numpy as np # type: ignore

# Data setup from previous steps
years_exp = np.array([1, 3, 5, 7, 10])
salaries = np.array([
    [50, 60, 70], 
    [80, 90, 100]
])

# Step 1: Access individual element
print("First year of experience:", years_exp[0])

# Step 2: Slice arrays (First two elements of first row)
print("First two salaries:", salaries[0, :2])

# Step 3: Access all rows for a specific column (Second column)
print("Second column salaries:", salaries[:, 1])

# Step 4: Negative indexing
print("Last year of experience:", years_exp[-1])

# --- "Try It" Section ---

# Reverse arrays using slicing
reversed_years = years_exp[::-1]
print("\nReversed years_exp:", reversed_years)

# Slice 2D arrays for subgroups of salaries 
# Example: Extracting a 2x2 sub-grid (Rows 0-2, Columns 1-3)
salary_subgroup = salaries[0:2, 1:3]
print("Subgroup of salaries (2x2 slice):\n", salary_subgroup)

First year of experience: 1
First two salaries: [50 60]
Second column salaries: [60 90]
Last year of experience: 10

Reversed years_exp: [10  7  5  3  1]
Subgroup of salaries (2x2 slice):
 [[ 60  70]
 [ 90 100]]


4. Reshaping and Dimensions

In [ ]:
import numpy as np # type: ignore

# Step 1: Reshape 1D array into 2x3 matrix for batch analysis
# np.arange(1, 7) creates [1, 2, 3, 4, 5, 6]
reshaped_exp = np.reshape(np.arange(1, 7), (2, 3))
print("Reshaped Experience Array:\n", reshaped_exp)

# Step 2: Flatten 2D arrays back into 1D
flattened_exp = reshaped_exp.flatten()
print("\nFlattened Array:", flattened_exp)

# Step 3: Transpose example (Swapping rows and columns)
print("\nTransposed Array:\n", reshaped_exp.T)

# --- "Try It" Section ---

# Reshape into different dimensions for modeling
# We have 6 elements, so we can try a 3x2 or a 6x1 dimension
try_it_3x2 = reshaped_exp.reshape(3, 2)
try_it_column = reshaped_exp.reshape(6, 1)

print("-" * 30)
print("Try It - 3x2 Reshape:\n", try_it_3x2)
print("\nTry It - 6x1 (Column Vector):\n", try_it_column)

Reshaped Experience Array:
 [[1 2 3]
 [4 5 6]]

Flattened Array: [1 2 3 4 5 6]

Transposed Array:
 [[1 4]
 [2 5]
 [3 6]]
------------------------------
Try It - 3x2 Reshape:
 [[1 2]
 [3 4]
 [5 6]]

Try It - 6x1 (Column Vector):
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


5. Broadcasting in NumPy

In [ ]:
import numpy as np # type: ignore

# Data setup: 2x3 Salary Matrix (from previous steps)
salaries = np.array([
    [50, 60, 70], 
    [80, 90, 100]
])

# Step 1: Add a bonus array using broadcasting
bonus = np.array([5, 10, 15])
salaries_with_bonus = salaries + bonus
print("Salaries after bonus:\n", salaries_with_bonus)

# --- "Try It" Section ---

# Multiply salaries by a scaling factor using broadcasting
# Example: 10% raise (scaling factor of 1.1)
scaling_factor = 1.1
scaled_salaries = salaries * scaling_factor

print("-" * 30)
print("Scaled Salaries (10% Raise):\n", scaled_salaries)

Salaries after bonus:
 [[ 55  70  85]
 [ 85 100 115]]
------------------------------
Scaled Salaries (10% Raise):
 [[ 55.  66.  77.]
 [ 88.  99. 110.]]


6. Statistical Operations

In [ ]:
import numpy as np # type: ignore

# Data setup from previous steps
years_exp = np.array([1, 3, 5, 7, 10])
salaries = np.array([
    [50, 60, 70], 
    [80, 90, 100]
])

# Step 1: Mean of years of experience
print("Mean experience:", np.mean(years_exp))

# Step 2: Standard deviation of experience
print("Std deviation of experience:", np.std(years_exp))

# Step 3: Max and Min salaries
print("Max salary:", np.max(salaries), "| Min salary:", np.min(salaries))

# Step 4: Sum of salaries
print("Sum of all salaries:", np.sum(salaries))

# --- "Try It" Section ---

# Compute median
median_exp = np.median(years_exp)

# Compute 25th and 75th percentiles for salaries
percentile_25 = np.percentile(salaries, 25)
percentile_75 = np.percentile(salaries, 75)

print("-" * 30)
print("Median experience:", median_exp)
print("25th Percentile of Salaries:", percentile_25)
print("75th Percentile of Salaries:", percentile_75)

Mean experience: 5.2
Std deviation of experience: 3.1240998703626617
Max salary: 100 | Min salary: 50
Sum of all salaries: 450
------------------------------
Median experience: 5.0
25th Percentile of Salaries: 62.5
75th Percentile of Salaries: 87.5


7. NumPy Functions on Arrays

In [ ]:
import numpy as np # type: ignore

# Data setup from previous steps
salaries = np.array([
    [50, 60, 70], 
    [80, 90, 100]
])

# Step 1: Apply trigonometric functions
# Angles in radians: 0, 45 degrees (pi/4), and 90 degrees (pi/2)
angles = np.array([0, np.pi/4, np.pi/2])
print("Sine of angles:", np.sin(angles))
print("Cosine of angles:", np.cos(angles))

# Step 2: Apply function along rows (axis=1)
# This sums the columns for each individual row
salary_sums = np.apply_along_axis(np.sum, 1, salaries)
print("Sum of Salaries per person:", salary_sums)

# --- "Try It" Section ---

# 1. Use np.sqrt() and np.log10() for transformations
sqrt_salaries = np.sqrt(salaries)
log_salaries = np.log10(salaries)

# 2. Apply a custom function (e.g., adding a 5% tax) using apply_along_axis
def add_tax(row):
    return row * 0.95  # Returns 95% of the original salary

taxed_salaries = np.apply_along_axis(add_tax, 1, salaries)

print("-" * 30)
print("Square Root of Salaries:\n", sqrt_salaries)
print("\nSalaries after 5% Tax (Custom Function):\n", taxed_salaries)

Sine of angles: [0.         0.70710678 1.        ]
Cosine of angles: [1.00000000e+00 7.07106781e-01 6.12323400e-17]
Sum of Salaries per person: [180 270]
------------------------------
Square Root of Salaries:
 [[ 7.07106781  7.74596669  8.36660027]
 [ 8.94427191  9.48683298 10.        ]]

Salaries after 5% Tax (Custom Function):
 [[47.5 57.  66.5]
 [76.  85.5 95. ]]


8. Integrating NumPy and Pandas for Analysis

In [30]:
import numpy as np
import pandas as pd

# Step 1: Create a NumPy array of random data (5 rows, 3 columns)
# randint(low, high, size)
data = np.random.randint(1, 50, size=(5, 3))

# Step 2: Convert the array into a DataFrame
df_data = pd.DataFrame(data, columns=['X', 'Y', 'Z'])
print("Generated Data:\n", df_data)

# Step 3: Apply NumPy functions to DataFrame columns
df_data['Log_X'] = np.log(df_data['X'])
df_data['Sqrt_Y'] = np.sqrt(df_data['Y'])
print("\nDataFrame with NumPy Transformations:\n", df_data)

# Step 4: Analyze data using Pandas correlation
print("\nCorrelation Matrix:\n", df_data.corr())

# --- "Try It" Section ---

# 1. Use np.mean() and np.median() for column statistics
# We apply these to the whole DataFrame
column_means = np.mean(df_data, axis=0)
column_medians = np.median(df_data, axis=0)

# 2. Apply other functions like np.square() or np.exp()
df_data['Square_Z'] = np.square(df_data['Z'])
df_data['Exp_X_Small'] = np.exp(df_data['X'] / 10) # Scaling down X to keep exp values readable

print("-" * 30)
print("Column Means:\n", column_means)
print("\nColumn Medians:\n", column_medians)
print("\nFinal DataFrame with Square and Exp:\n", df_data)

Generated Data:
     X   Y   Z
0   5   3  16
1  22  19  43
2  15  47  46
3  26  25   2
4  40   8  43

DataFrame with NumPy Transformations:
     X   Y   Z     Log_X    Sqrt_Y
0   5   3  16  1.609438  1.732051
1  22  19  43  3.091042  4.358899
2  15  47  46  2.708050  6.855655
3  26  25   2  3.258097  5.000000
4  40   8  43  3.688879  2.828427

Correlation Matrix:
                X         Y         Z     Log_X    Sqrt_Y
X       1.000000 -0.106174  0.240210  0.947175  0.017344
Y      -0.106174  1.000000  0.264084  0.164724  0.982494
Z       0.240210  0.264084  1.000000  0.283141  0.247470
Log_X   0.947175  0.164724  0.283141  1.000000  0.304947
Sqrt_Y  0.017344  0.982494  0.247470  0.304947  1.000000
------------------------------
Column Means:
 X         21.600000
Y         20.400000
Z         30.000000
Log_X      2.871101
Sqrt_Y     4.155006
dtype: float64

Column Medians:
 [22.         19.         43.          3.09104245  4.35889894]

Final DataFrame with Square and Exp:
     X   Y  

9. Importing and Summarizing Data Using Pandas

In [34]:
# Step 1: Save the DataFrame to a CSV file
# This depends on df_data from Procedure 8
df_data.to_csv('sample_data.csv', index=False)
print("Data saved to 'sample_data.csv'.")

# Step 2: Load the CSV file back into a new DataFrame
df_imported = pd.read_csv('sample_data.csv')
print("\nImported DataFrame:\n", df_imported.head())

# Step 3: Generate summary statistics
summary_stats = df_imported.describe()
print("\nSummary Statistics:\n", summary_stats)

# Step 4: Display column means and standard deviations
print("\nColumn Means:\n", df_imported.mean())
print("\nColumn Standard Deviations:\n", df_imported.std())

# --- TRY IT ---
# 1. Add a new calculated column
df_imported['Sum_XY'] = df_imported['X'] + df_imported['Y']

# 2. Save the modified DataFrame to a new CSV file
df_imported.to_csv('modified_sample_data.csv', index=False)
print("\nModified data saved to 'modified_sample_data.csv'.")

Data saved to 'sample_data.csv'.

Imported DataFrame:
     X   Y   Z     Log_X    Sqrt_Y  Square_Z  Exp_X_Small
0   5   3  16  1.609438  1.732051       256     1.648721
1  22  19  43  3.091042  4.358899      1849     9.025013
2  15  47  46  2.708050  6.855655      2116     4.481689
3  26  25   2  3.258097  5.000000         4    13.463738
4  40   8  43  3.688879  2.828427      1849    54.598150

Summary Statistics:
                X          Y          Z     Log_X    Sqrt_Y     Square_Z  \
count   5.000000   5.000000   5.000000  5.000000  5.000000     5.000000   
mean   21.600000  20.400000  30.000000  2.871101  4.155006  1214.800000   
std    13.011533  17.227884  19.836834  0.788239  1.979875  1000.239321   
min     5.000000   3.000000   2.000000  1.609438  1.732051     4.000000   
25%    15.000000   8.000000  16.000000  2.708050  2.828427   256.000000   
50%    22.000000  19.000000  43.000000  3.091042  4.358899  1849.000000   
75%    26.000000  25.000000  43.000000  3.258097  5.0000

10. Data Grouping and Aggregation

In [35]:
import pandas as pd # type: ignore
import numpy as np # type: ignore

# Step 1: Load the dataset with a safety check
try:
    df_kaggle = pd.read_csv('survey_results_public.csv')
    print("Stack Overflow Survey loaded successfully.")
except FileNotFoundError:
    df_kaggle = pd.read_csv('sample_data.csv')
    print("Survey file not found. Using sample_data.csv as a placeholder.")

# Step 2: Select relevant columns safely
# We check if 'Country' exists; if not, we use columns from your sample_data.csv
if 'Country' in df_kaggle.columns:
    target_cols = ['Country', 'EdLevel', 'YearsCodePro', 'ConvertedComp']
else:
    target_cols = ['X', 'Y', 'Z'] # Fallback for your current sample_data.csv

df_subset = df_kaggle[target_cols]

# Step 3: Clean the data
df_clean = df_subset.dropna().copy()

# Step 4: Categorize experience into groups
# If working with the real survey, we categorize by years
if 'YearsCodePro' in df_clean.columns:
    df_clean['YearsCodePro'] = pd.to_numeric(df_clean['YearsCodePro'], errors='coerce')
    df_clean = df_clean.dropna()
    df_clean['ExperienceLevel'] = np.where(df_clean['YearsCodePro'] >= 10, 'Senior', 'Junior')
else:
    # Placeholder logic for sample_data (X represents years)
    df_clean['ExperienceLevel'] = np.where(df_clean['X'] >= 25, 'Senior', 'Junior')

# Step 5 & 6: Group and Reset Index
group_by_col = 'Country' if 'Country' in df_clean.columns else 'Z'
value_col = 'ConvertedComp' if 'ConvertedComp' in df_clean.columns else 'Y'

grouped_data = df_clean.groupby([group_by_col, 'ExperienceLevel'])[value_col].mean().reset_index()
print("\nFormatted Grouped Data:\n", grouped_data.head())

# --- "Try It" Section ---

# 1. Change grouping to EdLevel and compute Median/Std
if 'EdLevel' in df_clean.columns:
    ed_stats = df_clean.groupby('EdLevel')['ConvertedComp'].agg(['median', 'std']).reset_index()
    print("\nEducation Stats (Median & Std):\n", ed_stats)

# 2. Explore top 10 countries with highest average compensation
if 'Country' in df_clean.columns:
    top_10 = grouped_data.groupby('Country')[value_col].mean().sort_values(ascending=False).head(10)
    print("\nTop 10 Highest Paying Countries:\n", top_10)

Survey file not found. Using sample_data.csv as a placeholder.

Formatted Grouped Data:
     Z ExperienceLevel     Y
0   2          Senior  25.0
1  16          Junior   3.0
2  43          Junior  19.0
3  43          Senior   8.0
4  46          Junior  47.0


IV. DATA AND OBSERVATION

In [38]:
import numpy as np
STUDENT_NAME = "Roxie Nacional"
STUDENT_ID = "TUPM-25-0363"

np.random.seed(STUDENT_ID)
data = np.random.randint(1, STUDENT_ID % 100 + 50, size=10)
print(f"{STUDENT_NAME}'s Array:", data)

mean_val = np.mean(data)
std_val = np.std(data)
print("Mean:", mean_val, "Std Dev:", std_val)

TypeError: Cannot cast scalar from dtype('<U12') to dtype('int64') according to the rule 'safe'

In [ ]:
import numpy as np
STUDENT_NAME = "Roxie Nacional"
STUDENT_ID = TUPM-25-0363

np.random.seed(STUDENT_ID)
matrix = np.random.randint(1, STUDENT_ID % 50 + 20, size=(3,4))
print(f"{STUDENT_NAME}'s Matrix:\n", matrix)

row_sums = np.sum(matrix, axis=1)
col_sums = np.sum(matrix, axis=0)
print("Row sums:", row_sums)
print("Column sums:", col_sums)

In [ ]:
import numpy as np
STUDENT_NAME = "Roxie Nacional"
STUDENT_ID = TUPM-25-0363

np.random.seed(STUDENT_ID)
arr3d = np.random.randint(0, STUDENT_ID % 20 + 10, size=(3,3,3))
print(f"{STUDENT_NAME}'s 3D Array:\n", arr3d)

slice_mid = arr3d[:,1,:]
print("Slice[:,1,:]:\n", slice_mid)

In [ ]:
import numpy as np
STUDENT_NAME = "Roxie Nacional"
STUDENT_ID = TUPM-25-0363

np.random.seed(STUDENT_ID)
x = np.random.randint(1, STUDENT_ID % 100 + 50, size=10)
filtered = x[(x>STUDENT_ID%50) & (x<STUDENT_ID%100)]
print(f"{STUDENT_NAME}'s Original:", x)
print("Filtered subset:", filtered)

In [ ]:
import numpy as np
STUDENT_NAME = "Roxie Nacional"
STUDENT_ID = TUPM-25-0363

np.random.seed(STUDENT_ID)
A = np.random.randint(1, STUDENT_ID % 50 + 20, size=(2,2))
B = np.random.randint(1, STUDENT_ID % 50 + 20, size=(2,2))
print("Matrix A:\n", A)
print("Matrix B:\n", B)

product = A @ B
det_A = np.linalg.det(A)
print("A @ B:\n", product)
print("Determinant of A:", det_A)

In [ ]:
import numpy as np
STUDENT_NAME = "Roxie Nacional"
STUDENT_ID = TUPM-25-0363

angles = np.linspace(0, 2*np.pi, 8)
sine_vals = np.sin(angles)
cos_vals = np.cos(angles)
print(f"{STUDENT_NAME}'s Angles:", angles)
print("Sine:", sine_vals)
print("Cosine:", cos_vals)

In [ ]:
import numpy as np
STUDENT_NAME = "Roxie Nacional"
STUDENT_ID = TUPM-25-0363

np.random.seed(STUDENT_ID)
arr = np.random.randint(1, STUDENT_ID % 50 + 20, size=(4,4))
arr[::2, ::2] = 0
print(f"{STUDENT_NAME}'s Modified 4x4 Array:\n", arr)

In [ ]:
import numpy as np
STUDENT_NAME = "Roxie Nacional"
STUDENT_ID = TUPM-25-0363

np.random.seed(STUDENT_ID)
scores = np.random.randint(0, STUDENT_ID % 100 + 50, 10)
grades = np.where(scores>=STUDENT_ID%70,'Pass','Fail')
print(f"{STUDENT_NAME}'s Scores:", scores)
print("Grades:", grades)

In [ ]:
import numpy as np
STUDENT_NAME = "Roxie Nacional"
STUDENT_ID = TUPM-25-0363

np.random.seed(STUDENT_ID)
arr = np.random.randint(1, STUDENT_ID % 50 + 20, size=(3,4))
flat_arr = arr.flatten()
transposed_arr = arr.T
print("Original array:\n", arr)
print("Flattened:", flat_arr)
print("Transposed:\n", transposed_arr)

In [ ]:
import numpy as np
STUDENT_NAME = "Roxie Nacional"
STUDENT_ID = TUPM-25-0363

np.random.seed(STUDENT_ID)
arr = np.random.randint(1, STUDENT_ID % 50 + 20, (3,3))
mask = arr % 2 == 0
arr[mask] = -1
print("Array with conditional replacements:\n", arr)

In [ ]:
import numpy as np
import pandas as pd
STUDENT_NAME = "Roxie Nacional"
STUDENT_ID = TUPM-25-0363

np.random.seed(STUDENT_ID)
df = pd.DataFrame({
 'Name': [STUDENT_NAME]*5,
 'Score': np.random.randint(STUDENT_ID%50,
STUDENT_ID%100+50,5),
 'YearsCodePro': np.random.randint(0, STUDENT_ID%20+10,5)
})
print(df)

In [ ]:
import numpy as np
import pandas as pd
STUDENT_NAME = "Roxie Nacional"
STUDENT_ID = TUPM-25-0363

np.random.seed(STUDENT_ID)
df = pd.DataFrame({
'EdLevel': ['Bachelor','Master','PhD','Bachelor','Master'],
# Corrected to use a functional salary range, e.g., 40000 to 150000
'ConvertedComp': np.random.randint(40000, 150000, 5)
})
avg_salary = df.groupby('EdLevel')['ConvertedComp'].mean()
print(avg_salary)

In [ ]:
import numpy as np
import pandas as pd
STUDENT_NAME = "Roxie Nacional"
STUDENT_ID = TUPM-25-0363

np.random.seed(STUDENT_ID)

df = pd.DataFrame({
 'Country': ['Philippines','USA','UK','Canada','Germany'],
 'ConvertedComp': np.random.randint(40000, 150000, 5)
})
top5 = df.sort_values(by='ConvertedComp', ascending=False)
print(top5)

In [ ]:
mport numpy as np
import pandas as pd
STUDENT_NAME = "Roxie Nacional"
STUDENT_ID = TUPM-25-0363

np.random.seed(STUDENT_ID)
df = pd.DataFrame({
 'Name':[STUDENT_NAME]*5,
 'YearsCodePro': np.random.randint(0, STUDENT_ID%20+10,5)
})
high_exp = df[df['YearsCodePro']>STUDENT_ID%10]
print(high_exp)

In [ ]:
mport numpy as np
import pandas as pd
STUDENT_NAME = "Roxie Nacional"
STUDENT_ID = TUPM-25-0363

np.random.seed(STUDENT_ID)

df = pd.DataFrame({'ConvertedComp': np.random.randint(40000,
150000, 5)})

bins = [0, 50000, 100000, 150000, 200000]
labels = ['0-50k', '50-100k', '100-150k', '>150k']

df['Bracket'] = pd.cut(df['ConvertedComp'], bins=bins, labels=labels)
print(df)

In [ ]:
import numpy as np
import pandas as pd
STUDENT_NAME = "Roxie Nacional"
STUDENT_ID = TUPM-25-0363

np.random.seed(STUDENT_ID)

# Original Code Issue:
# np.random.randint(STUDENT_ID%40000, STUDENT_ID%150000, 5)
# -> np.random.randint(12345, 12345, 5) which is a zero-length range.

# Corrected Code: Using a functional salary range (40000 to 150000)
df = pd.DataFrame({'ConvertedComp': np.random.randint(40000,150000, 5)})

df['LogComp'] = np.log(df['ConvertedComp'])
print(df)

In [ ]:
import numpy as np
import pandas as pd
STUDENT_NAME = "Roxie Nacional"
STUDENT_ID = TUPM-25-0363

np.random.seed(STUDENT_ID)

df = pd.DataFrame({
'YearsCodePro': np.random.randint(0, STUDENT_ID%20+10, 5),
'ConvertedComp': np.random.randint(40000, 150000, 5)
})

corr_matrix = df.corr()
print(corr_matrix)

In [ ]:
import numpy as np
import pandas as pd
STUDENT_NAME = "Roxie Nacional"
STUDENT_ID = TUPM-25-0363

np.random.seed(STUDENT_ID)

df = pd.DataFrame({
'EdLevel':['Bachelor','Master','PhD','Bachelor','Master'],
'ConvertedComp': np.random.randint(40000, 150000, 5)
})

# Calculate mean, median, and standard deviation for each 'EdLevel'
summary =
df.groupby('EdLevel')['ConvertedComp'].agg(['mean','median','std']).rese
t_index()
print(summary)

In [ ]:
import numpy as np
import pandas as pd
STUDENT_NAME = "Roxie Nacional"
STUDENT_ID = TUPM-25-0363

np.random.seed(STUDENT_ID)

# Generate salaries: [100727, 136195, 130612, 100727, 95233]
df = pd.DataFrame({'ConvertedComp': np.random.randint(40000,
150000, 5)})

threshold = 110000

# Create the 'HighPay' column using np.where()
df['HighPay'] = np.where(df['ConvertedComp'] > threshold, 'Yes', 'No')
print(df)
DataFrame with Yes/No
column based on threshold, "Yes", "No"

print(df)

In [ ]:
mport numpy as np
import pandas as pd
STUDENT_NAME = "Roxie Nacional"
STUDENT_ID = TUPM-25-0363

np.random.seed(STUDENT_ID)

df = pd.DataFrame({
'Country': ['Philippines','USA','UK','Canada','Germany'],
'ConvertedComp': np.random.randint(40000, 150000, 5)
})

# Group by 'Country' and calculate the mean and max 'ConvertedComp'
top_countries =
df.groupby('Country')['ConvertedComp'].agg(['mean','max'])
print(top_countries)