1. Using try-except Blocks for Safe NumPy Operations

In [2]:
import numpy as np
try:
 a = np.array([1, 2, 3])
 b = np.array([[1], [2], [3]])
 result = a + b
 print(result)
except ValueError as e:
 print(f"Broadcasting error: {e}")

[[2 3 4]
 [3 4 5]
 [4 5 6]]


2. Creating and Using Identity Matrices in Computation

In [3]:
identity = np.eye(3)
matrix = np.array([[2, 3, 4], [1, 0, 6], [7, 8, 9]])
print("Matrix + Identity:\n", matrix + identity)

Matrix + Identity:
 [[ 3.  3.  4.]
 [ 1.  1.  6.]
 [ 7.  8. 10.]]


3. Detecting NaNs and Invalid Data in Arrays (NumPy)

In [4]:
data = np.array([1, 2, np.nan, 4, np.inf])
cleaned = data[np.isfinite(data)]
print("Cleaned Data:", cleaned)

Cleaned Data: [1. 2. 4.]


4. Handling Missing Data in Pandas

In [5]:
import pandas as pd
df = pd.DataFrame({
 "Name": ["Alice", "Bob", "Charlie", None],
 "Score": [85, None, 92, 88]
})
df_cleaned = df.dropna()
print("Cleaned DataFrame:\n", df_cleaned)

Cleaned DataFrame:
       Name  Score
0    Alice   85.0
2  Charlie   92.0


5. Applying NumPy Functions to Pandas Columns

In [6]:
df = pd.DataFrame({
 "X": [1, 2, 3],
 "Y": [4, 5, 6]
})
df["Log_X"] = np.log(df["X"])
df["Sqrt_Y"] = np.sqrt(df["Y"])
print("Transformed DataFrame:\n", df)

Transformed DataFrame:
    X  Y     Log_X    Sqrt_Y
0  1  4  0.000000  2.000000
1  2  5  0.693147  2.236068
2  3  6  1.098612  2.449490


In [ ]:
import pandas as pd
import numpy as np


# --- 1. SETUP & DATA LOADING ---
# Using the exact filename from your VS Code sidebar
file_path = 'Most Popular Programming Languages.csv'
df = pd.read_csv(file_path)

# Standardize column names by removing leading/trailing spaces
df.columns = df.columns.str.strip()

# Set Month as index
# Note: If your CSV uses 'Date', change 'Month' to 'Date' below
df['Month'] = pd.to_datetime(df['Month'])
df.set_index('Month', inplace=True)

# --- 2. DYNAMIC LANGUAGE ASSIGNMENT ---
# This finds the actual column names (e.g., "React Worldwide (%)") 
# based on your assigned index 7 (React) and 8 (Swift)
try:
    lang_a = [col for col in df.columns if 'React' in col][0]
    lang_b = [col for col in df.columns if 'Swift' in col][0]
    print(f"Targeting Columns: {lang_a} and {lang_b}")
except IndexError:
    print("Error: Could not find columns containing 'React' or 'Swift'.")

# --- 3. TASK 1: GROWTH ANALYSIS (For React) ---
# Compute month-to-month growth rate
df['Growth_Rate'] = df[lang_a].pct_change() * 100

# Rolling statistics (6-month window as per Lab instructions)
df['Moving_Avg'] = df[lang_a].rolling(window=6).mean()
df['Moving_STD'] = df[lang_a].rolling(window=6).std()

# Classify growth phases using NumPy
conditions = [(df['Growth_Rate'] > 5), (df['Growth_Rate'] < -5)]
choices = ['Growth', 'Decline']
df['Phase'] = np.select(conditions, choices, default='Stable')

# --- 4. TASK 2: LIFECYCLE CLASSIFICATION ---
mean_growth = df['Growth_Rate'].mean()
std_growth = df['Growth_Rate'].std()

lifecycle_conds = [
    (df['Growth_Rate'] > 0) & (df['Growth_Rate'] < mean_growth), # Introduction
    (df['Growth_Rate'] > mean_growth),                           # Growth
    (df['Growth_Rate'].abs() <= 1),                             # Maturity
    (df['Growth_Rate'] < 0) & (df['Growth_Rate'] < (-1 * std_growth)) # Decline
]
lifecycle_choices = ['Introduction', 'Growth', 'Maturity', 'Decline']
df['Lifecycle_Phase'] = np.select(lifecycle_conds, lifecycle_choices, default='Maturity')

# --- 5. TASK 3: COMPARATIVE METRICS ---
correlation = df[lang_a].corr(df[lang_b])
dominance_ratio = (df[lang_a] > df[lang_b]).mean() * 100
rpi = df[lang_a].mean() / df[lang_b].mean()

# --- 6. OUTPUTS ---
print("\n" + "="*30)
print(f"STATISTICAL SUMMARY: {lang_a}")
print("="*30)
print(df[lang_a].describe())

print("\n--- Phase Counts ---")
print(df['Phase'].value_counts())

print("\n--- Comparative Metrics (React vs Swift) ---")
print(f"Correlation Coefficient: {correlation:.4f}")
print(f"Dominance Ratio: {dominance_ratio:.2f}%")
print(f"Relative Performance Index: {rpi:.4f}")

# Preview the results table
print("\n--- Final Classification Preview ---")
cols_to_show = [lang_a, 'Growth_Rate', 'Phase', 'Lifecycle_Phase']
print(df[cols_to_show].tail(10))

FileNotFoundError: [Errno 2] No such file or directory: 'Most Popular Programming Languages.csv'